from .HomePage import *
from .test_view_speaker_detail import *
from .test_models import *
from .test_managers import *
from .test_view_talk_list import *
from .test_view_talk_list_detail import *
from .test_models_talk import *
from .test_models_course import *
from .test_models_media import *
from .test_templatetags import *